site_name: Extended Resources for FactorySimPy

theme:
  name: material  # optional: for Material Design theme

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          #paths: ['ReservablePriorityReqStore', 'PriorityReqStore']  # Specify the paths to your modules here
          paths: 
          - ReservablePriorityReqStore/ReservablePriorityReqStore.py
          - PriorityReqStore/PriorityReqStore.py # Specify the paths to your modules here

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences  # (important for code blocks inside lists/admonitions)

nav:
  - Home: index.md
      
  - API Reference:
      - ReservablePriorityReqStore: reservablepriorityreqstore.md
      - PriorityReqStore: priorityreqstore.md